### ISSUE TITLE
Support Tika not running on the same server

### ISSUE THREAD

**Issue by dready** [4teamwork/ftw.tika#29]
Hi,

i did not find where to configure that tika is running on a different server therefore i assume there is none.
But it would be nice if there where one so you could for example use docker and run tika in one instance and plone in another.

thx

**Comment by jone** [comment]
Sorry for the late response
It seems you already have found the solution to use the `host` option in the ZCML, as you documented here: https://github.com/4teamwork/ftw.tika#different-host-buildout-example
Thanks! :wink:
